### ISSUE TITLE
Hire Frontender

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/cyber.fund#425]
We are looking for front-end engineer!
### Necessary skills:
- Experienced in React
- Reactive programming using Meteor or Meatier
- Cross platform development
- Analitycs driven decisions
- Test driven approach
- Skilled Github collaborator
- Responsive thinking
- Ability to create interfaces using something like Material UI
### Forthcoming task:
- Adopt BitShares UI for http://satoshi.fund purposes. Integration with [Blockcypher API](http://dev.blockcypher.com/), self-hosted BitShares node ([Grpahene API](http://docs.bitshares.org/api/index.html)) and cyberFund API.
### Benefits:
- Salary in bitcoins, 
- Open source projects only
- Equity and tokens options
- Blockchain industry
- Cryptocurrency experienced team
### How to apply:

Submit links on your works, open source projects, thoughts about our stack or recommend somebody.

Russian knowledge is a plus but not a requirement!

**Comment by Undeadlol1** [comment]
@21xhipster , меня заинтересовала ваша вакансия. 
Я около года знаком с Метеором, последние два месяца успешно применяю реакт в метеоре. До этого писал на Ангуларе.
В гитхабе у меня есть два хобби проекта:
[Kopilka](https://github.com/Undeadlol1/kopilka) - гирбирдное (мобайл и веб) приложение, написанное на Метеоре 1.2, Ангуларе и Ionic.
[Anylearn ](https://github.com/Undeadlol1/anylearn) - веб приложение с вики-подобным функционалом написанное на Meteor 1.3 и React.
Я ознакомился с кодом вашего проекта, и сделал парочку пулл реквестов, исправляющих баги и улучшающих внешний вид страниц.
Как вам удобнее всего вести переписку? Здесь? Имейл? Скайп? 
На всякий случай оставляю свои контакты: 
email: undeadlol1@mail.ru 
skype: paleyfreelance 
vk: /paleyblog

**Comment by 21xhipster** [comment]
@Undeadlol1 Сделал запрос в скайп!

**Comment by gamedevsam** [comment]
Hello, I'm an early adopter of cyber.fund (joined in Nov 2015) and I think I can help accelerate development. I'm not sure I can fulfil the role of CTO, since I have a full time job, and can only contribute on a part time basis, but I can be a strong asset for focused feature development.

I created the initial prototype and first consumer release of [Storj Driveshare](https://storj.io/share.html). I also have extensive experience with open source development since I am one of the owners of the [HaxeFlixel project](https://github.com/orgs/HaxeFlixel/people).

I don't know a lot about React, but I am working on a meteor project currently (I can't share it publicly yet, but I can show it privately). I learn quickly, and can get stuff done!

Website: http://www.sambatista.com
Github: https://github.com/gamedevsam
Email: sambatista@protonmail.com

Let me know if you think a part-time contractor setup could work for us.

- Sam

**Comment by 21xhipster** [comment]
@gamedevsam Sure. Lets talk by skype: starodubcev

**Comment by Srirangan** [comment]
@21xhipster Same here. I'm employed elsewhere, but I have the time and skills to contribute.

This is me:

- [srirangan.net/about](http://srirangan.net/about)
- [github.com/srirangan](http://www.github.com/Srirangan)
- [linkedin.com/srirangan](http://www.linkedin.com/in/srirangan)

**Comment by 21xhipster** [comment]
@litvintech @tomarcafe Насколько нам сейчас актуален поиск фронтендера? Или стоит пока разобраться с тем что и как мы делаем прежде чем вписывать нового человека?

**Comment by tomarcafe** [comment]
поиск фронтендера был актуален в феврале. теперь мне просто пофиг
